[package]
name = "FinSc-Multiset-Core-Wiki"
version = "0.1.0"
ipkg = "FinSc-Multiset-Core-Wiki.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"
